## 1. Importing Nescessary Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("/kaggle/input/datasets/adityayadav01/imdb-datasets/IMDB Dataset.csv",engine="python")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.shape

(50000, 2)

In [5]:
df['sentiment'].value_counts()  ## Data is balanced

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## 2. Text Cleaning
1. Remove HTML tags
2. Remove Special Characters
3. Converting every thing to lower case
4. Remove stop words
5. stemming

In [8]:
## 1. Removing HTML tags
import re
clean = re.compile('<.*?>')
re.sub(clean,"",df.iloc[1].review)

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [9]:
## function to clean html tags
def remove_html(data):
  clean = re.compile('<.*?>')
  return re.sub(clean,'',data)

In [10]:
df['review'] = df['review'].apply(remove_html)

In [11]:
## converting text into lower case
def lower(data):
  return data.lower()

In [12]:
df['review'] = df['review'].apply(lower)

In [13]:
df['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [14]:
## to remove special character
text = "I am a $ant"

def remove_special(text):
  x = ""
  for i in text:
    if i.isalnum():
      x = x+i
    else:
      x=x+" "

  print(x)

In [15]:
remove_special(df['review'])

In [16]:
df['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [17]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
from nltk.corpus import stopwords

In [19]:
stop_words = stopwords.words('english')
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [20]:
## removing stopwords
def remove_srwds(data):

  x= []
  for i in data.split():
    if i not in stop_words:
      x.append(i)
  y = x[:]
  x.clear()
  return y

In [21]:
df['review'] = df['review'].apply(remove_srwds)

In [22]:
df['review']

0        [one, reviewers, mentioned, watching, 1, oz, e...
1        [wonderful, little, production., filming, tech...
2        [thought, wonderful, way, spend, time, hot, su...
3        [basically, there's, family, little, boy, (jak...
4        [petter, mattei's, "love, time, money", visual...
                               ...
49995    [thought, movie, right, good, job., creative, ...
49996    [bad, plot,, bad, dialogue,, bad, acting,, idi...
49997    [catholic, taught, parochial, elementary, scho...
49998    [going, disagree, previous, comment, side, mal...
49999    [one, expects, star, trek, movies, high, art,,...
Name: review, Length: 50000, dtype: object

In [23]:
## applying stemming
from nltk.stem.porter import PorterStemmer

In [24]:
ps = PorterStemmer()

In [25]:
y = []

def stemmer(data):
  for i in data:
    y.append(ps.stem(i))

  z = y[:]
  y.clear()
  return z

In [26]:
df['review'] = df['review'].apply(stemmer)

In [27]:
stemmer(['I','Love','loving','lover','loved','loves'])

['i', 'love', 'love', 'lover', 'love', 'love']

In [28]:
## joining back text
def join_back(data):
  return " ".join(data)

In [29]:
df['review'] = df['review'].apply(join_back)

In [30]:
df.review

0        one review mention watch 1 oz episod hooked. r...
1        wonder littl production. film techniqu unassum...
2        thought wonder way spend time hot summer weeke...
3        basic there' famili littl boy (jake) think the...
4        petter mattei' "love time money" visual stun f...
                               ...
49995    thought movi right good job. creativ origin fi...
49996    bad plot, bad dialogue, bad acting, idiot dire...
49997    cathol taught parochi elementari school nuns, ...
49998    go disagre previou comment side maltin one. se...
49999    one expect star trek movi high art, fan expect...
Name: review, Length: 50000, dtype: object

In [31]:
## most frequent words in corpus
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000)

In [32]:
X = cv.fit_transform(df['review']).toarray()

In [33]:
X.shape

(50000, 10000)

In [34]:
X[0].max()

np.int64(6)

In [35]:
y = df.iloc[:,-1]

## 3. Feature Engineering

In [36]:
y.shape

(50000,)

In [37]:
## applying label encoder for the output column
from sklearn.preprocessing import LabelEncoder

In [38]:
le = LabelEncoder()
df['sentiment'] = le.fit_transform(df['sentiment'])

In [39]:
df.head()

                                              review  sentiment
0  one review mention watch 1 oz episod hooked. r...          1
1  wonder littl production. film techniqu unassum...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic there' famili littl boy (jake) think the...          0
4  petter mattei' "love time money" visual stun f...          1

In [40]:
df['sentiment'].value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

## 4. Train Test Split

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.3)

## 5. Modelling

In [42]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [43]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [44]:
gnb.fit(X_train,y_train)
mnb.fit(X_train,y_train)
bnb.fit(X_train,y_train)

BernoulliNB()

In [45]:
y_pred1 = gnb.predict(X_test)
y_pred2 = mnb.predict(X_test)
y_pred3 = bnb.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred1))
print(accuracy_score(y_test,y_pred2))
print(accuracy_score(y_test,y_pred3))

0.7178666666666667
0.8486666666666667
0.8514