In [5]:
# pip install optuna

In [10]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
import optuna
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [7]:
# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [13]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-04-01 04:42:09,258] A new study created in memory with name: no-name-f580106d-07ab-4de4-9527-109353cd6a74
[I 2026-04-01 04:42:13,195] Trial 0 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 179, 'max_depth': 14}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:15,149] Trial 1 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 91, 'max_depth': 10}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:17,916] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 111, 'max_depth': 3}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:23,626] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 172, 'max_depth': 18}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:25,650] Trial 4 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 61, 'max_depth': 10}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:28,831] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 186, 'max_depth': 20}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:30,809] Trial 6 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 150, 'max_depth': 3}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:32,806] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 15}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:34,004] Trial 8 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 193, 'max_depth': 14}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:34,744] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 110, 'max_depth': 10}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:36,146] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 7}. Best is trial 0 with value: 0.7765363128491621.
[I 2026-04-01 04:42:37,983] Trial 11 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 200, 'max_depth': 16}. Best is trial 11 with value: 0.7783985102420856.
[I 2026-04-01 04:42:39,061] Trial 12 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 160, 'max_depth': 15}. Best is trial 11 with value: 0.7783985102420856.
[I 2026-04-01 04:42:40,346] Trial 13 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 198, 'max_depth': 18}. Best is trial 11 with value: 0.7783985102420856.
[I 2026-04-01 04:42:41,206] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 136, 'max_depth': 13}. Best is trial 11 with value: 0.7783985102420856.
[I 2026-04-01 04:42:42,281] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 174, 'max_depth': 17}. Best is trial 11 with value: 0.7783985102420856.
[I 2026-04-01 04:42:43,343] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 171, 'max_depth': 12}. Best is trial 11 with value: 0.7783985102420856.
[I 2026-04-01 04:42:44,137] Trial 17 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 127, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:44,547] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 62, 'max_depth': 20}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:45,153] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:45,933] Trial 20 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 128, 'max_depth': 7}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:46,717] Trial 21 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 128, 'max_depth': 6}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:47,193] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 5}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:48,331] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 138, 'max_depth': 8}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:49,608] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 118, 'max_depth': 12}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:50,145] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 18}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:51,299] Trial 26 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 152, 'max_depth': 8}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:52,000] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 104, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:52,870] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 137, 'max_depth': 11}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:53,398] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 80, 'max_depth': 14}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:54,235] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 126, 'max_depth': 13}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:55,409] Trial 31 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 184, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:56,576] Trial 32 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 185, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:57,599] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 17}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:42:58,766] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 182, 'max_depth': 19}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:00,112] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:01,469] Trial 36 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 162, 'max_depth': 9}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:02,533] Trial 37 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 119, 'max_depth': 4}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:03,490] Trial 38 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 19}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:04,740] Trial 39 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 191, 'max_depth': 13}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:05,811] Trial 40 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 169, 'max_depth': 17}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:06,948] Trial 41 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 181, 'max_depth': 14}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:08,086] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 178, 'max_depth': 15}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:09,316] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 190, 'max_depth': 11}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:10,567] Trial 44 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 14}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:11,460] Trial 45 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 142, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:12,414] Trial 46 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 17}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:13,118] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 18}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:14,511] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 175, 'max_depth': 19}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-04-01 04:43:16,042] Trial 49 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 157, 'max_depth': 15}. Best is trial 17 with value: 0.7802607076350093.

In [14]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 127, 'max_depth': 16}

In [17]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)   ## dictionary unpacking

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Samplers in Optuna (act as Randomised Search CV)

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [19]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-04-01 04:47:22,569] A new study created in memory with name: no-name-5dd6c68e-1e39-4f85-8a81-1f9cb2305333
[I 2026-04-01 04:47:23,228] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 70, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-01 04:47:27,216] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 200, 'max_depth': 9}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-01 04:47:30,246] Trial 2 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 118, 'max_depth': 19}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:31,837] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 20}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:34,921] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 17}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:37,526] Trial 5 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 177, 'max_depth': 14}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:39,143] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 19}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:40,140] Trial 7 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 71, 'max_depth': 9}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:41,324] Trial 8 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 17}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:42,433] Trial 9 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 124, 'max_depth': 19}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:42,856] Trial 10 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 65, 'max_depth': 9}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:43,716] Trial 11 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 147, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:44,199] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 76, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:45,343] Trial 13 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 20}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:46,016] Trial 14 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 69, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:46,794] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 5}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:47,377] Trial 16 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 63, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:47,886] Trial 17 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 76, 'max_depth': 18}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:49,099] Trial 18 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 18}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:50,137] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 165, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:51,316] Trial 20 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 191, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:52,047] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:52,453] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 61, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:53,461] Trial 23 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 164, 'max_depth': 17}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:54,126] Trial 24 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 113, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:54,710] Trial 25 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 89, 'max_depth': 17}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:55,720] Trial 26 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 170, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:47:58,657] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 20}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:01,223] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 114, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:02,628] Trial 29 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 91, 'max_depth': 20}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:04,743] Trial 30 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 170, 'max_depth': 16}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:06,799] Trial 31 finished with value: 0.756052141527002 and parameters: {'n_estimators': 173, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:08,383] Trial 32 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 18}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:09,721] Trial 33 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 93, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:11,016] Trial 34 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 189, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:11,458] Trial 35 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 55, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:12,240] Trial 36 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:13,625] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:14,141] Trial 38 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 56, 'max_depth': 3}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:15,043] Trial 39 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:16,247] Trial 40 finished with value: 0.756052141527002 and parameters: {'n_estimators': 189, 'max_depth': 9}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:16,778] Trial 41 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 86, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:17,833] Trial 42 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 183, 'max_depth': 5}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:18,688] Trial 43 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 139, 'max_depth': 5}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:19,066] Trial 44 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 55, 'max_depth': 20}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:19,391] Trial 45 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 51, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:20,230] Trial 46 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 136, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:20,918] Trial 47 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 110, 'max_depth': 14}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:21,605] Trial 48 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 110, 'max_depth': 14}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-04-01 04:48:22,778] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 190, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420856.

In [20]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420856
Best hyperparameters: {'n_estimators': 118, 'max_depth': 19}

In [21]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## GridSearchCV

In [22]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [23]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-04-01 04:49:40,638] A new study created in memory with name: no-name-48510d7c-8c61-49a1-87f2-ac9321d9e313
[I 2026-04-01 04:49:41,846] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-04-01 04:49:43,348] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-04-01 04:49:43,913] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:44,933] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:45,984] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:46,500] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:48,127] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:49,137] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:50,415] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:52,377] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:53,719] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:54,951] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:56,082] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-04-01 04:49:56,385] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-04-01 04:49:57,004] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-04-01 04:49:57,323] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [24]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [25]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# Optuna Visualizations

In [26]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [27]:
# 1. Optimization History
plot_optimization_history(study).show()

In [28]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [29]:
# 3. Slice Plot
plot_slice(study).show()

In [30]:
# 4. Contour Plot
plot_contour(study).show()

In [31]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

# Optimizing Multiple ML Models

In [32]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [33]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [34]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2026-04-01 04:54:47,199] A new study created in memory with name: no-name-039e3566-3504-48ea-8e6d-d0aaaa9727fa
[I 2026-04-01 04:54:47,326] Trial 0 finished with value: 0.6797020484171323 and parameters: {'classifier': 'SVM', 'C': 78.50439737402517, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.6797020484171323.
[I 2026-04-01 04:54:47,399] Trial 1 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.21142917238971826, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:54:53,460] Trial 2 finished with value: 0.7597765363128492 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 269, 'learning_rate': 0.02329510135261682, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:00,722] Trial 3 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 86, 'learning_rate': 0.10113400900401437, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:00,835] Trial 4 finished with value: 0.7579143389199254 and parameters: {'classifier': 'SVM', 'C': 4.421964650643386, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:00,902] Trial 5 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.23106371996260697, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:02,907] Trial 6 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 184, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:04,060] Trial 7 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 51, 'learning_rate': 0.06612593125589551, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:07,196] Trial 8 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 267, 'learning_rate': 0.21033735413021465, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:08,478] Trial 9 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 150, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-01 04:55:08,555] Trial 10 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.1283535997824066, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7728119180633147.
[I 2026-04-01 04:55:08,624] Trial 11 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.11103168036816789, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7728119180633147.
[I 2026-04-01 04:55:08,688] Trial 12 finished with value: 0.74487895716946 and parameters: {'classifier': 'SVM', 'C': 0.755396638662329, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 10 with value: 0.7728119180633147.
[I 2026-04-01 04:55:08,748] Trial 13 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4543572877309072, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 13 with value: 0.7839851024208566.
[I 2026-04-01 04:55:08,832] Trial 14 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.8152164361982925, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:08,913] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.8529894617381726, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:10,466] Trial 16 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 189, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:10,544] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.702791421472762, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:10,611] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.303205058352198, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,266] Trial 19 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 127, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,351] Trial 20 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 16.367962930021847, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,458] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 20.70881817240186, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,501] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.185493583127122, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,594] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.33951906541558, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,862] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 53.88451467467241, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,916] Trial 25 finished with value: 0.7579143389199254 and parameters: {'classifier': 'SVM', 'C': 4.440305734349302, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:11,950] Trial 26 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.1240320714889473, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:12,014] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.176435332324543, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:17,645] Trial 28 finished with value: 0.7225325884543762 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 234, 'learning_rate': 0.01010814557445527, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:19,246] Trial 29 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 297, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:19,405] Trial 30 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 32.862645833754684, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:19,472] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.285223586833833, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:19,524] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.978376612975256, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:19,601] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.620796268669545, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:19,653] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.36648748176927, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:19,733] Trial 35 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.098009889851134, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:20,509] Trial 36 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 109, 'learning_rate': 0.26772748029748067, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:20,585] Trial 37 finished with value: 0.7411545623836125 and parameters: {'classifier': 'SVM', 'C': 29.37713103474106, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:20,645] Trial 38 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 2.3440950616125047, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:26,090] Trial 39 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 223, 'learning_rate': 0.02689160542066867, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.7858472998137801.
[I 2026-04-01 04:55:26,125] Trial 40 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.702481868377505, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:26,158] Trial 41 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5284938753506405, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:26,218] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.727101211223945, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:26,259] Trial 43 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.5169492215411209, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:26,300] Trial 44 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 4.192052121428481, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:26,646] Trial 45 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 51, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:27,003] Trial 46 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 98.86596664039003, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:27,044] Trial 47 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.610089560807881, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:30,981] Trial 48 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 226, 'learning_rate': 0.010316484420318208, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 40 with value: 0.7858472998137803.
[I 2026-04-01 04:55:31,021] Trial 49 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.4622484301135836, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 40 with value: 0.7858472998137803.

In [35]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.702481868377505, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7858472998137803

In [36]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 36
GradientBoosting     8
RandomForest         6
Name: count, dtype: int64

In [37]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.743948
RandomForest        0.765363
SVM                 0.772191
Name: value, dtype: float64

In [38]:
# 1. Optimization History
plot_optimization_history(study).show()

In [39]:
# 3. Slice Plot
plot_slice(study).show()

In [40]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()